# Generated by Django 5.0.3 on 2024-04-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app003', '0005_cart_livraison_order_delete_commande_cart_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
